POST {{apiUrl}}/events
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "type": "REVIEW",
  "action": "DELETE",
  "reviewId": "1",
  "content": "",
  "attachedPhotoIds": [1],
  "userId": "1",
  "placeId": "1"
}